AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Taurus - Lambda Layer nested stack

Metadata:
  TemplateName: lambda-layer-stack.yaml
  TemplateType: Lambda Layer
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Taurus
  Modification History:
    - 1.0.0  - Oct 04, 2023   -- Initial Version
  Resources: 
    - Resources
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label:
        default: "Project Name And Environment:"
      Parameters:
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRepository
      - CiBuild
    #################################### Code Repository Bucket ####################################
    - Label:
        default: "Code Repository S3 Bucket:"
      Parameters:
      - CodeRepositoryS3Bucket
  ParameterLabels:
    #################################### Project Name and Environment ##############################
    ProjectName:
      default: "Project Name."
    Environment:
      default: "Environment Name."
    #################################### GitHub Attributes #########################################
    GitHubRef:
      default: "GitHub Ref."
    GitHubURL:
      default: "GitHub URL."
    GitHubWFRunNumber:
      default: "GitHub Workflow Run Number."
    GitHubSHA:
      default: "GitHub SHA"
    GitHubRepository:
      default: "GitHub Repository."
    CiBuild:
      default: "Ci Build."
    StackName:
      default: "Stack Name."
    #################################### Code Repository Bucket ####################################
    CodeRepositoryS3Bucket:
      default: "Code Repository S3 Bucket."
    #################################### Lambda Layer ##############################################
    LambdaLayerName: 
      default: "Lammba Function Execution Role Arn."
    LambdaLayerDescription:
      default: "Lambda Function Timeout in Seconds."
    LambdaLayerRuntime: 
      default: "Lambda Runtime."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: project
    Description: "The Project Name for which the custom resource will be used."
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: "[a-z]*"
    ConstraintDescription: "The length should be between 5 and 30, must contain only lowercase alphabets."
  Environment:
    Default: devl
    Description: "The Environment Name."
    Type: String
    AllowedValues: ["devl", "test", "prod"]
    ConstraintDescription: "The Environment must be devl / test or prod"
  ###################################### GitHub Attributes #########################################
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### Code Repository Bucket ####################################
  CodeRepositoryS3Bucket:
    Default: subhamay-projects-repository-us-east-1
    Description: "S3 Bucket Storing The Lambda Code."
    Type: String
    MinLength: 10
    MaxLength: 63
    AllowedPattern: "[a-z][a-z0-9-.]*"
    ConstraintDescription: "The length should be between 3 and 63, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  ###################################### Lambda Layer ####################################
  LambdaLayerBaseName:
    Default: my-lib
    Description: The base name of the Lambda Layer
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: "[a-zA-Z-_]*"
    ConstraintDescription: The length should be between 5 and 30, must contain only letters and should start with an uppercase letter. 
  LambdaLayerDescription:
    Default: Lambda Layer Description
    Description: Lambda Execution Description
    Type: String
    MinLength: 20
    MaxLength: 60
    AllowedPattern: "[a-zA-Z\ -_]*"
    ConstraintDescription: The length should be between 20 and 60, must contain only letters and should start with an uppercase letter. 
  LambdaLayerRuntime:
    Default: python3.8
    Description: "Lambda Runtime (Python 3.7, 3.8 or 3.9)"
    Type: String
    AllowedValues: [python3.7 ,python3.8, python3.9]
    ConstraintDescription: "The Lambda runtime should be either Python 3.7, 3.8 or 3.9"
Resources:
  ###################################### Lambda Layer ##############################################
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
        - arm64
      CompatibleRuntimes:
        - !Ref LambdaLayerRuntime
      Content:
        S3Bucket: !Ref CodeRepositoryS3Bucket
        S3Key: !Sub '${GitHubRepository}/lambda-layer/${LambdaLayerBaseName}.zip'
      Description: !Ref LambdaLayerDescription
      LayerName: !Sub '${ProjectName}-${LambdaLayerBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      LicenseInfo: Subhamay
Outputs:
  LambdaLayerArn: 
    Description: The Arn of the Lambda Function
    Value: !Ref LambdaLayer
